name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t smc-523 .
    - name: Runs tests
      run: docker run -v smcompiler:/code_data --name smc-tests smc-523 pytest -s

